Resources:
    IdeasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: ideaId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: visibility
            AttributeType: S
          - AttributeName: authorSlug
            AttributeType: S
          - AttributeName: title
            AttributeType: S
          - AttributeName: createdDate
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
          - AttributeName: commentsCount
            AttributeType: N
          - AttributeName: likesCount
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: ideaId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.ideasTableName}
        GlobalSecondaryIndexes:
          - IndexName: ideasById
            KeySchema:
              - AttributeName: ideaId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: allIdeasByDate
            KeySchema:
              - AttributeName: sortKey
                KeyType: HASH
              - AttributeName: createdDate
                KeyType: RANGE
            Projection:
                ProjectionType: ALL
          - IndexName: publicIdeasByDate
            KeySchema:
              - AttributeName: visibility
                KeyType: HASH
              - AttributeName: createdDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: publicIdeasByName
            KeySchema:
              - AttributeName: visibility
                KeyType: HASH
              - AttributeName: title
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: publicIdeasByCommentsCount
            KeySchema:
              - AttributeName: visibility
                KeyType: HASH
              - AttributeName: commentsCount
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: publicIdeasByLikesCount
            KeySchema:
              - AttributeName: visibility
                KeyType: HASH
              - AttributeName: likesCount
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: ideasBySlugAndDate
            KeySchema:
              - AttributeName: authorSlug
                KeyType: HASH
              - AttributeName: createdDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: myIdeasByDate
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdDate
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: myIdeasByName
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: title
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: myIdeasByCommentsCount
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: commentsCount
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: myIdeasByLikesCount
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: likesCount
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
